module Evergreen.Migrate.V12 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V10.Types
import Evergreen.V12.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V10.Types.FrontendModel -> ModelMigration Evergreen.V12.Types.FrontendModel Evergreen.V12.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V10.Types.BackendModel -> ModelMigration Evergreen.V12.Types.BackendModel Evergreen.V12.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V10.Types.FrontendMsg -> MsgMigration Evergreen.V12.Types.FrontendMsg Evergreen.V12.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V10.Types.ToBackend -> MsgMigration Evergreen.V12.Types.ToBackend Evergreen.V12.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V10.Types.BackendMsg -> MsgMigration Evergreen.V12.Types.BackendMsg Evergreen.V12.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V10.Types.ToFrontend -> MsgMigration Evergreen.V12.Types.ToFrontend Evergreen.V12.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V10.Types.BackendModel -> Evergreen.V12.Types.BackendModel
migrate_Types_BackendModel old =
    { currentSaltIndex = old.currentSaltIndex
    , passiveUsers = old.passiveUsers |> Dict.map (\k -> migrate_Types_User)
    , activeSessions = old.activeSessions |> Dict.map (\k -> migrate_Types_Session)
    , currentTime = old.currentTime
    }


migrate_Types_FrontendModel : Evergreen.V10.Types.FrontendModel -> Evergreen.V12.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , settings = old.settings |> migrate_Types_Settings
    , statistic = old.statistic |> List.map migrate_Types_PastDictation
    , authorised = old.authorised
    , usersCount = old.usersCount
    }


migrate_Types_AuthModel : Evergreen.V10.Types.AuthModel -> Evergreen.V12.Types.AuthModel
migrate_Types_AuthModel old =
    { username = old.username
    , password = old.password
    , passwordVisibility = old.passwordVisibility
    , failed = old.failed |> migrate_Types_LoginFail
    }


migrate_Types_AuthMsg : Evergreen.V10.Types.AuthMsg -> Evergreen.V12.Types.AuthMsg
migrate_Types_AuthMsg old =
    case old of
        Evergreen.V10.Types.SetUsername p0 ->
            Evergreen.V12.Types.SetUsername p0

        Evergreen.V10.Types.SetPassword p0 ->
            Evergreen.V12.Types.SetPassword p0

        Evergreen.V10.Types.SetVisibility p0 ->
            Evergreen.V12.Types.SetVisibility p0

        Evergreen.V10.Types.TryLogin p0 p1 ->
            Evergreen.V12.Types.TryLogin p0 p1

        Evergreen.V10.Types.TryRegister p0 p1 ->
            Evergreen.V12.Types.TryRegister p0 p1

        Evergreen.V10.Types.ToInfo ->
            Evergreen.V12.Types.ToInfo

        Evergreen.V10.Types.WithoutLogin ->
            Evergreen.V12.Types.WithoutLogin


migrate_Types_Bucket : Evergreen.V10.Types.Bucket -> Evergreen.V12.Types.Bucket
migrate_Types_Bucket old =
    old |> List.map migrate_Types_PastDictation


migrate_Types_Dictation : Evergreen.V10.Types.Dictation -> Evergreen.V12.Types.Dictation
migrate_Types_Dictation old =
    old


migrate_Types_FrontendMsg : Evergreen.V10.Types.FrontendMsg -> Evergreen.V12.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V10.Types.UrlClicked p0 ->
            Evergreen.V12.Types.UrlClicked p0

        Evergreen.V10.Types.UrlChanged p0 ->
            Evergreen.V12.Types.UrlChanged p0

        Evergreen.V10.Types.NoOpFrontendMsg ->
            Evergreen.V12.Types.NoOpFrontendMsg

        Evergreen.V10.Types.PageMsg p0 ->
            Evergreen.V12.Types.PageMsg (p0 |> migrate_Types_PageMsg)

        Evergreen.V10.Types.Back ->
            Evergreen.V12.Types.Back

        Evergreen.V10.Types.SetSettings p0 ->
            Evergreen.V12.Types.SetSettings (p0 |> migrate_Types_Settings)

        Evergreen.V10.Types.OnHover p0 ->
            Evergreen.V12.Types.OnHover (p0 |> migrate_Types_Hover)

        Evergreen.V10.Types.Logout ->
            Evergreen.V12.Types.Logout

        Evergreen.V10.Types.FinishedDictation p0 p1 p2 p3 ->
            Evergreen.V12.Types.FinishedDictation p0 (p1 |> migrate_Types_Lesson) p2 p3

        Evergreen.V10.Types.ChangePage p0 ->
            Evergreen.V12.Types.ChangePage (p0 |> migrate_Types_Page)


migrate_Types_Hover : Evergreen.V10.Types.Hover -> Evergreen.V12.Types.Hover
migrate_Types_Hover old =
    old |> migrate_Types_Bucket


migrate_Types_KeyboardKey : Evergreen.V10.Types.KeyboardKey -> Evergreen.V12.Types.KeyboardKey
migrate_Types_KeyboardKey old =
    case old of
        Evergreen.V10.Types.Character p0 ->
            Evergreen.V12.Types.Character p0

        Evergreen.V10.Types.Control p0 ->
            Evergreen.V12.Types.Control p0


migrate_Types_Layout : Evergreen.V10.Types.Layout -> Evergreen.V12.Types.Layout
migrate_Types_Layout old =
    case old of
        Evergreen.V10.Types.Neo ->
            Evergreen.V12.Types.Neo

        Evergreen.V10.Types.NeoQwertz ->
            Evergreen.V12.Types.NeoQwertz

        Evergreen.V10.Types.Bone ->
            Evergreen.V12.Types.Bone

        Evergreen.V10.Types.AdNW ->
            Evergreen.V12.Types.AdNW

        Evergreen.V10.Types.KOY ->
            Evergreen.V12.Types.KOY

        Evergreen.V10.Types.NeoQwerty ->
            Evergreen.V12.Types.NeoQwerty

        Evergreen.V10.Types.Vou ->
            Evergreen.V12.Types.Vou

        Evergreen.V10.Types.Mine ->
            Evergreen.V12.Types.Mine


migrate_Types_Lesson : Evergreen.V10.Types.Lesson -> Evergreen.V12.Types.Lesson
migrate_Types_Lesson old =
    { layout = Nothing
    , title = old.title
    , content = old.content
    }


migrate_Types_LoginFail : Evergreen.V10.Types.LoginFail -> Evergreen.V12.Types.LoginFail
migrate_Types_LoginFail old =
    case old of
        Evergreen.V10.Types.NotAsked ->
            Evergreen.V12.Types.NotAsked

        Evergreen.V10.Types.WrongUsernameOrPassword ->
            Evergreen.V12.Types.WrongUsernameOrPassword

        Evergreen.V10.Types.UsernameOrPasswordInvalid ->
            Evergreen.V12.Types.UsernameOrPasswordInvalid


migrate_Types_Menu : Evergreen.V10.Types.Menu -> Evergreen.V12.Types.Menu
migrate_Types_Menu old =
    { current = old.current |> Maybe.map migrate_Types_Lesson
    }


migrate_Types_Page : Evergreen.V10.Types.Page -> Evergreen.V12.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V10.Types.MenuPage p0 ->
            Evergreen.V12.Types.MenuPage (p0 |> migrate_Types_Menu)

        Evergreen.V10.Types.TypingPage p0 ->
            Evergreen.V12.Types.TypingPage (p0 |> migrate_Types_TypingModel)

        Evergreen.V10.Types.TypingStatisticPage p0 ->
            Evergreen.V12.Types.TypingStatisticPage (p0 |> migrate_Types_PastDictation)

        Evergreen.V10.Types.SettingsPage p0 ->
            Evergreen.V12.Types.SettingsPage p0

        Evergreen.V10.Types.StatisticPage p0 ->
            Evergreen.V12.Types.StatisticPage (p0 |> migrate_Types_Hover)

        Evergreen.V10.Types.AuthPage p0 ->
            Evergreen.V12.Types.AuthPage (p0 |> migrate_Types_AuthModel)

        Evergreen.V10.Types.InfoPage ->
            Evergreen.V12.Types.InfoPage


migrate_Types_PageMsg : Evergreen.V10.Types.PageMsg -> Evergreen.V12.Types.PageMsg
migrate_Types_PageMsg old =
    case old of
        Evergreen.V10.Types.TypingMsg p0 ->
            Evergreen.V12.Types.TypingMsg (p0 |> migrate_Types_TypingMsg)

        Evergreen.V10.Types.AuthMsg p0 ->
            Evergreen.V12.Types.AuthMsg (p0 |> migrate_Types_AuthMsg)

        Evergreen.V10.Types.SettingsMsg p0 ->
            Evergreen.V12.Types.SettingsMsg (p0 |> migrate_Types_SettingsMsg)


migrate_Types_PastDictation : Evergreen.V10.Types.PastDictation -> Evergreen.V12.Types.PastDictation
migrate_Types_PastDictation old =
    { errors = old.errors
    , lesson = old.lesson |> migrate_Types_Lesson
    , duration = old.duration
    , finished = old.finished
    }


migrate_Types_Session : Evergreen.V10.Types.Session -> Evergreen.V12.Types.Session
migrate_Types_Session old =
    { user = old.user |> migrate_Types_User
    , created = old.created
    }


migrate_Types_Settings : Evergreen.V10.Types.Settings -> Evergreen.V12.Types.Settings
migrate_Types_Settings old =
    { blockOnError = old.blockOnError |> migrate_Types_WaitingFor
    , fontSize = old.fontSize
    , paddingLeft = old.paddingLeft
    , paddingRight = old.paddingRight
    , layout = old.layout |> migrate_Types_Layout
    , theme = old.theme |> migrate_Types_Theme
    }


migrate_Types_SettingsMsg : Evergreen.V10.Types.SettingsMsg -> Evergreen.V12.Types.SettingsMsg
migrate_Types_SettingsMsg old =
    case old of
        Evergreen.V10.Types.SetLayer p0 ->
            Evergreen.V12.Types.SetLayer p0


migrate_Types_Theme : Evergreen.V10.Types.Theme -> Evergreen.V12.Types.Theme
migrate_Types_Theme old =
    { name = old.name |> migrate_Types_ThemeName
    , dark = old.dark
    , rounding = old.rounding
    , borderWidth = old.borderWidth
    }


migrate_Types_ThemeName : Evergreen.V10.Types.ThemeName -> Evergreen.V12.Types.ThemeName
migrate_Types_ThemeName old =
    case old of
        Evergreen.V10.Types.WheatField ->
            Evergreen.V12.Types.WheatField

        Evergreen.V10.Types.ElectricFields ->
            Evergreen.V12.Types.ElectricFields

        Evergreen.V10.Types.CandyLand ->
            Evergreen.V12.Types.CandyLand

        Evergreen.V10.Types.NeoClassic ->
            Evergreen.V12.Types.NeoClassic

        Evergreen.V10.Types.Dracula ->
            Evergreen.V12.Types.Dracula


migrate_Types_ToBackend : Evergreen.V10.Types.ToBackend -> Evergreen.V12.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V10.Types.UpdateSettings p0 ->
            Evergreen.V12.Types.UpdateSettings (p0 |> migrate_Types_Settings)

        Evergreen.V10.Types.GetSettings ->
            Evergreen.V12.Types.GetSettings

        Evergreen.V10.Types.InsertUser p0 p1 ->
            Evergreen.V12.Types.InsertUser p0 p1

        Evergreen.V10.Types.InsertSession p0 p1 ->
            Evergreen.V12.Types.InsertSession p0 p1

        Evergreen.V10.Types.GetSession ->
            Evergreen.V12.Types.GetSession

        Evergreen.V10.Types.RemoveSession ->
            Evergreen.V12.Types.RemoveSession

        Evergreen.V10.Types.ConsStatistic p0 ->
            Evergreen.V12.Types.ConsStatistic (p0 |> migrate_Types_PastDictation)

        Evergreen.V10.Types.GetStatistic ->
            Evergreen.V12.Types.GetStatistic

        Evergreen.V10.Types.GetUserCount ->
            Evergreen.V12.Types.GetUserCount


migrate_Types_ToFrontend : Evergreen.V10.Types.ToFrontend -> Evergreen.V12.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V10.Types.GotSettings p0 ->
            Evergreen.V12.Types.GotSettings (p0 |> migrate_Types_Settings)

        Evergreen.V10.Types.KickOut ->
            Evergreen.V12.Types.KickOut

        Evergreen.V10.Types.RegisterFailed ->
            Evergreen.V12.Types.RegisterFailed

        Evergreen.V10.Types.LoginSuccessful ->
            Evergreen.V12.Types.LoginSuccessful

        Evergreen.V10.Types.LoginFailed ->
            Evergreen.V12.Types.LoginFailed

        Evergreen.V10.Types.UpdateStatistic p0 ->
            Evergreen.V12.Types.UpdateStatistic (p0 |> List.map migrate_Types_PastDictation)

        Evergreen.V10.Types.UpdateUserCount p0 ->
            Evergreen.V12.Types.UpdateUserCount p0


migrate_Types_TypingModel : Evergreen.V10.Types.TypingModel -> Evergreen.V12.Types.TypingModel
migrate_Types_TypingModel old =
    { dictation = old.dictation |> migrate_Types_Dictation
    , madeError = old.madeError
    , errors = old.errors
    , layer = old.layer
    , lesson = old.lesson |> migrate_Types_Lesson
    , duration = old.duration
    , paused = old.paused
    , showKeyboard = old.showKeyboard
    }


migrate_Types_TypingMsg : Evergreen.V10.Types.TypingMsg -> Evergreen.V12.Types.TypingMsg
migrate_Types_TypingMsg old =
    case old of
        Evergreen.V10.Types.KeyDown p0 ->
            Evergreen.V12.Types.KeyDown (p0 |> migrate_Types_KeyboardKey)

        Evergreen.V10.Types.KeyUp p0 ->
            Evergreen.V12.Types.KeyUp (p0 |> migrate_Types_KeyboardKey)

        Evergreen.V10.Types.TickTypingTime ->
            Evergreen.V12.Types.TickTypingTime

        Evergreen.V10.Types.Pause ->
            Evergreen.V12.Types.Pause

        Evergreen.V10.Types.Play ->
            Evergreen.V12.Types.Play

        Evergreen.V10.Types.ToggleKeyboard ->
            Evergreen.V12.Types.ToggleKeyboard

        Evergreen.V10.Types.Exit ->
            Evergreen.V12.Types.Exit


migrate_Types_User : Evergreen.V10.Types.User -> Evergreen.V12.Types.User
migrate_Types_User old =
    { username = old.username
    , passwordHash = old.passwordHash
    , passwordSalt = old.passwordSalt
    , settings = old.settings |> migrate_Types_Settings
    , pastDictations = old.pastDictations |> List.map migrate_Types_PastDictation
    }


migrate_Types_WaitingFor : Evergreen.V10.Types.WaitingFor -> Evergreen.V12.Types.WaitingFor
migrate_Types_WaitingFor old =
    case old of
        Evergreen.V10.Types.OneBackspace ->
            Evergreen.V12.Types.OneBackspace

        Evergreen.V10.Types.CorrectLetter ->
            Evergreen.V12.Types.CorrectLetter
