module Evergreen.Migrate.V16 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V15.Translation
import Evergreen.V15.Types
import Evergreen.V16.Translation
import Evergreen.V16.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V15.Types.FrontendModel -> ModelMigration Evergreen.V16.Types.FrontendModel Evergreen.V16.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V15.Types.BackendModel -> ModelMigration Evergreen.V16.Types.BackendModel Evergreen.V16.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V15.Types.FrontendMsg -> MsgMigration Evergreen.V16.Types.FrontendMsg Evergreen.V16.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V15.Types.ToBackend -> MsgMigration Evergreen.V16.Types.ToBackend Evergreen.V16.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V15.Types.BackendMsg -> MsgMigration Evergreen.V16.Types.BackendMsg Evergreen.V16.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V15.Types.ToFrontend -> MsgMigration Evergreen.V16.Types.ToFrontend Evergreen.V16.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V15.Types.FrontendModel -> Evergreen.V16.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , settings = old.settings |> migrate_Types_Settings
    , statistic = old.statistic |> List.map migrate_Types_PastDictation
    , authorised = old.authorised
    , usersCount = old.usersCount
    }


migrate_Translation_Language : Evergreen.V15.Translation.Language -> Evergreen.V16.Translation.Language
migrate_Translation_Language old =
    case old of
        Evergreen.V15.Translation.German ->
            Evergreen.V16.Translation.German

        Evergreen.V15.Translation.English ->
            Evergreen.V16.Translation.English


migrate_Types_AuthModel : Evergreen.V15.Types.AuthModel -> Evergreen.V16.Types.AuthModel
migrate_Types_AuthModel old =
    { username = old.username
    , password = old.password
    , passwordVisibility = old.passwordVisibility
    , failed = old.failed |> migrate_Types_LoginFail
    }


migrate_Types_AuthMsg : Evergreen.V15.Types.AuthMsg -> Evergreen.V16.Types.AuthMsg
migrate_Types_AuthMsg old =
    case old of
        Evergreen.V15.Types.SetUsername p0 ->
            Evergreen.V16.Types.SetUsername p0

        Evergreen.V15.Types.SetPassword p0 ->
            Evergreen.V16.Types.SetPassword p0

        Evergreen.V15.Types.SetVisibility p0 ->
            Evergreen.V16.Types.SetVisibility p0

        Evergreen.V15.Types.TryLogin p0 p1 ->
            Evergreen.V16.Types.TryLogin p0 p1

        Evergreen.V15.Types.TryRegister p0 p1 ->
            Evergreen.V16.Types.TryRegister p0 p1

        Evergreen.V15.Types.ToInfo ->
            Evergreen.V16.Types.ToInfo

        Evergreen.V15.Types.WithoutLogin ->
            Evergreen.V16.Types.WithoutLogin

        Evergreen.V15.Types.ToggleTranslation ->
            Evergreen.V16.Types.ToggleTranslation


migrate_Types_Bucket : Evergreen.V15.Types.Bucket -> Evergreen.V16.Types.Bucket
migrate_Types_Bucket old =
    old |> List.map migrate_Types_PastDictation


migrate_Types_Dictation : Evergreen.V15.Types.Dictation -> Evergreen.V16.Types.Dictation
migrate_Types_Dictation old =
    old


migrate_Types_FrontendMsg : Evergreen.V15.Types.FrontendMsg -> Evergreen.V16.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V15.Types.UrlClicked p0 ->
            Evergreen.V16.Types.UrlClicked p0

        Evergreen.V15.Types.UrlChanged p0 ->
            Evergreen.V16.Types.UrlChanged p0

        Evergreen.V15.Types.NoOpFrontendMsg ->
            Evergreen.V16.Types.NoOpFrontendMsg

        Evergreen.V15.Types.PageMsg p0 ->
            Evergreen.V16.Types.PageMsg (p0 |> migrate_Types_PageMsg)

        Evergreen.V15.Types.Back ->
            Evergreen.V16.Types.Back

        Evergreen.V15.Types.SetSettings p0 ->
            Evergreen.V16.Types.SetSettings (p0 |> migrate_Types_Settings)

        Evergreen.V15.Types.OnHover p0 ->
            Evergreen.V16.Types.OnHover (p0 |> migrate_Types_Hover)

        Evergreen.V15.Types.Logout ->
            Evergreen.V16.Types.Logout

        Evergreen.V15.Types.FinishedDictation p0 p1 p2 p3 ->
            Evergreen.V16.Types.FinishedDictation p0 (p1 |> migrate_Types_Lesson) p2 p3

        Evergreen.V15.Types.ChangePage p0 ->
            Evergreen.V16.Types.ChangePage (p0 |> migrate_Types_Page)


migrate_Types_Hover : Evergreen.V15.Types.Hover -> Evergreen.V16.Types.Hover
migrate_Types_Hover old =
    old |> migrate_Types_Bucket


migrate_Types_KeyboardKey : Evergreen.V15.Types.KeyboardKey -> Evergreen.V16.Types.KeyboardKey
migrate_Types_KeyboardKey old =
    case old of
        Evergreen.V15.Types.Character p0 ->
            Evergreen.V16.Types.Character p0

        Evergreen.V15.Types.Control p0 ->
            Evergreen.V16.Types.Control p0


migrate_Types_Layout : Evergreen.V15.Types.Layout -> Evergreen.V16.Types.Layout
migrate_Types_Layout old =
    case old of
        Evergreen.V15.Types.Neo ->
            Evergreen.V16.Types.Neo

        Evergreen.V15.Types.NeoQwertz ->
            Evergreen.V16.Types.NeoQwertz

        Evergreen.V15.Types.Bone ->
            Evergreen.V16.Types.Bone

        Evergreen.V15.Types.AdNW ->
            Evergreen.V16.Types.AdNW

        Evergreen.V15.Types.KOY ->
            Evergreen.V16.Types.KOY

        Evergreen.V15.Types.NeoQwerty ->
            Evergreen.V16.Types.NeoQwerty

        Evergreen.V15.Types.Vou ->
            Evergreen.V16.Types.Vou

        Evergreen.V15.Types.Mine ->
            Evergreen.V16.Types.Mine


migrate_Types_Lesson : Evergreen.V15.Types.Lesson -> Evergreen.V16.Types.Lesson
migrate_Types_Lesson old =
    { layout = old.layout |> Maybe.map migrate_Types_Layout
    , title = old.title
    , content = old.content
    }


migrate_Types_LoginFail : Evergreen.V15.Types.LoginFail -> Evergreen.V16.Types.LoginFail
migrate_Types_LoginFail old =
    case old of
        Evergreen.V15.Types.NotAsked ->
            Evergreen.V16.Types.NotAsked

        Evergreen.V15.Types.WrongUsernameOrPassword ->
            Evergreen.V16.Types.WrongUsernameOrPassword

        Evergreen.V15.Types.UsernameOrPasswordInvalid ->
            Evergreen.V16.Types.UsernameOrPasswordInvalid


migrate_Types_Menu : Evergreen.V15.Types.Menu -> Evergreen.V16.Types.Menu
migrate_Types_Menu old =
    { current = old.current |> Maybe.map migrate_Types_Lesson
    }


migrate_Types_Mods : Evergreen.V15.Types.Mods -> Evergreen.V16.Types.Mods
migrate_Types_Mods old =
    old


migrate_Types_Page : Evergreen.V15.Types.Page -> Evergreen.V16.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V15.Types.MenuPage p0 ->
            Evergreen.V16.Types.MenuPage (p0 |> migrate_Types_Menu)

        Evergreen.V15.Types.TypingPage p0 ->
            Evergreen.V16.Types.TypingPage (p0 |> migrate_Types_TypingModel)

        Evergreen.V15.Types.TypingStatisticPage p0 ->
            Evergreen.V16.Types.TypingStatisticPage (p0 |> migrate_Types_TypingStatisticModel)

        Evergreen.V15.Types.SettingsPage p0 ->
            Evergreen.V16.Types.SettingsPage p0

        Evergreen.V15.Types.StatisticPage p0 ->
            Evergreen.V16.Types.StatisticPage (p0 |> migrate_Types_Hover)

        Evergreen.V15.Types.AuthPage p0 ->
            Evergreen.V16.Types.AuthPage (p0 |> migrate_Types_AuthModel)

        Evergreen.V15.Types.InfoPage ->
            Evergreen.V16.Types.InfoPage


migrate_Types_PageMsg : Evergreen.V15.Types.PageMsg -> Evergreen.V16.Types.PageMsg
migrate_Types_PageMsg old =
    case old of
        Evergreen.V15.Types.TypingMsg p0 ->
            Evergreen.V16.Types.TypingMsg (p0 |> migrate_Types_TypingMsg)

        Evergreen.V15.Types.AuthMsg p0 ->
            Evergreen.V16.Types.AuthMsg (p0 |> migrate_Types_AuthMsg)

        Evergreen.V15.Types.SettingsMsg p0 ->
            Evergreen.V16.Types.SettingsMsg (p0 |> migrate_Types_SettingsMsg)


migrate_Types_PastDictation : Evergreen.V15.Types.PastDictation -> Evergreen.V16.Types.PastDictation
migrate_Types_PastDictation old =
    { errors = old.errors
    , lesson = old.lesson |> migrate_Types_Lesson
    , duration = old.duration
    , finished = old.finished
    }


migrate_Types_Settings : Evergreen.V15.Types.Settings -> Evergreen.V16.Types.Settings
migrate_Types_Settings old =
    { blockOnError = old.blockOnError |> migrate_Types_WaitingFor
    , fontSize = old.fontSize
    , paddingLeft = old.paddingLeft
    , paddingRight = old.paddingRight
    , layout = old.layout |> migrate_Types_Layout
    , theme = old.theme |> migrate_Types_Theme
    , language = old.language |> migrate_Translation_Language
    }


migrate_Types_SettingsMsg : Evergreen.V15.Types.SettingsMsg -> Evergreen.V16.Types.SettingsMsg
migrate_Types_SettingsMsg old =
    case old of
        Evergreen.V15.Types.SetLayer p0 ->
            Evergreen.V16.Types.SetLayer p0


migrate_Types_Theme : Evergreen.V15.Types.Theme -> Evergreen.V16.Types.Theme
migrate_Types_Theme old =
    { name = old.name |> migrate_Types_ThemeName
    , dark = old.dark
    , rounding = old.rounding
    , borderWidth = old.borderWidth
    }


migrate_Types_ThemeName : Evergreen.V15.Types.ThemeName -> Evergreen.V16.Types.ThemeName
migrate_Types_ThemeName old =
    case old of
        Evergreen.V15.Types.WheatField ->
            Evergreen.V16.Types.WheatField

        Evergreen.V15.Types.ElectricFields ->
            Evergreen.V16.Types.ElectricFields

        Evergreen.V15.Types.CandyLand ->
            Evergreen.V16.Types.CandyLand

        Evergreen.V15.Types.NeoClassic ->
            Evergreen.V16.Types.NeoClassic

        Evergreen.V15.Types.Dracula ->
            Evergreen.V16.Types.Dracula


migrate_Types_TypingModel : Evergreen.V15.Types.TypingModel -> Evergreen.V16.Types.TypingModel
migrate_Types_TypingModel old =
    { dictation = old.dictation |> migrate_Types_Dictation
    , madeError = old.madeError
    , errors = old.errors
    , mods = old.mods |> migrate_Types_Mods
    , lesson = old.lesson |> migrate_Types_Lesson
    , duration = old.duration
    , paused = old.paused
    , showKeyboard = old.showKeyboard
    , textOffset = 0
    , textSpeed = 0
    }


migrate_Types_TypingMsg : Evergreen.V15.Types.TypingMsg -> Evergreen.V16.Types.TypingMsg
migrate_Types_TypingMsg old =
    case old of
        Evergreen.V15.Types.KeyDown p0 ->
            Evergreen.V16.Types.KeyDown (p0 |> migrate_Types_KeyboardKey)

        Evergreen.V15.Types.KeyUp p0 ->
            Evergreen.V16.Types.KeyUp (p0 |> migrate_Types_KeyboardKey)

        Evergreen.V15.Types.TickTypingTime ->
            Evergreen.V16.Types.TickTypingTime

        Evergreen.V15.Types.Pause ->
            Evergreen.V16.Types.Pause

        Evergreen.V15.Types.Play ->
            Evergreen.V16.Types.Play

        Evergreen.V15.Types.ToggleKeyboard ->
            Evergreen.V16.Types.ToggleKeyboard

        Evergreen.V15.Types.Exit ->
            Evergreen.V16.Types.Exit


migrate_Types_TypingStatisticModel : Evergreen.V15.Types.TypingStatisticModel -> Evergreen.V16.Types.TypingStatisticModel
migrate_Types_TypingStatisticModel old =
    { past = old.past |> migrate_Types_PastDictation
    , allPoints = old.allPoints
    }


migrate_Types_WaitingFor : Evergreen.V15.Types.WaitingFor -> Evergreen.V16.Types.WaitingFor
migrate_Types_WaitingFor old =
    case old of
        Evergreen.V15.Types.OneBackspace ->
            Evergreen.V16.Types.OneBackspace

        Evergreen.V15.Types.CorrectLetter ->
            Evergreen.V16.Types.CorrectLetter
