module Evergreen.Migrate.V29 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V28.Translation
import Evergreen.V28.Types
import Evergreen.V29.Translation
import Evergreen.V29.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V28.Types.FrontendModel -> ModelMigration Evergreen.V29.Types.FrontendModel Evergreen.V29.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V28.Types.BackendModel -> ModelMigration Evergreen.V29.Types.BackendModel Evergreen.V29.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V28.Types.FrontendMsg -> MsgMigration Evergreen.V29.Types.FrontendMsg Evergreen.V29.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V28.Types.ToBackend -> MsgMigration Evergreen.V29.Types.ToBackend Evergreen.V29.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V28.Types.BackendMsg -> MsgMigration Evergreen.V29.Types.BackendMsg Evergreen.V29.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V28.Types.ToFrontend -> MsgMigration Evergreen.V29.Types.ToFrontend Evergreen.V29.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V28.Types.FrontendModel -> Evergreen.V29.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , settings = old.settings |> migrate_Types_Settings
    , statistic = old.statistic |> List.map migrate_Types_PastDictation
    , authorised = old.authorised
    , appStatistic = old.appStatistic |> migrate_Types_AppStatistic
    }


migrate_Translation_Language : Evergreen.V28.Translation.Language -> Evergreen.V29.Translation.Language
migrate_Translation_Language old =
    case old of
        Evergreen.V28.Translation.German ->
            Evergreen.V29.Translation.German

        Evergreen.V28.Translation.English ->
            Evergreen.V29.Translation.English


migrate_Types_AppStatistic : Evergreen.V28.Types.AppStatistic -> Evergreen.V29.Types.AppStatistic
migrate_Types_AppStatistic old =
    { userCount = old.userCount
    , pastDictationCount = old.pastDictationCount
    , pastDictationCurve = []
    }


migrate_Types_AuthModel : Evergreen.V28.Types.AuthModel -> Evergreen.V29.Types.AuthModel
migrate_Types_AuthModel old =
    { username = old.username
    , password = old.password
    , passwordVisibility = old.passwordVisibility
    , failed = old.failed |> migrate_Types_LoginFail
    }


migrate_Types_Dictation : Evergreen.V28.Types.Dictation -> Evergreen.V29.Types.Dictation
migrate_Types_Dictation old =
    old


migrate_Types_Hover : Evergreen.V28.Types.Hover -> Evergreen.V29.Types.Hover
migrate_Types_Hover old =
    old |> migrate_Types_PastDictationBucket


migrate_Types_Layout : Evergreen.V28.Types.Layout -> Evergreen.V29.Types.Layout
migrate_Types_Layout old =
    case old of
        Evergreen.V28.Types.Neo ->
            Evergreen.V29.Types.Neo

        Evergreen.V28.Types.NeoQwertz ->
            Evergreen.V29.Types.NeoQwertz

        Evergreen.V28.Types.Bone ->
            Evergreen.V29.Types.Bone

        Evergreen.V28.Types.AdNW ->
            Evergreen.V29.Types.AdNW

        Evergreen.V28.Types.KOY ->
            Evergreen.V29.Types.KOY

        Evergreen.V28.Types.NeoQwerty ->
            Evergreen.V29.Types.NeoQwerty

        Evergreen.V28.Types.Vou ->
            Evergreen.V29.Types.Vou

        Evergreen.V28.Types.Mine ->
            Evergreen.V29.Types.Mine

        Evergreen.V28.Types.Noted ->
            Evergreen.V29.Types.Noted


migrate_Types_Lesson : Evergreen.V28.Types.Lesson -> Evergreen.V29.Types.Lesson
migrate_Types_Lesson old =
    { layout = old.layout |> Maybe.map migrate_Types_Layout
    , title = old.title
    , content = old.content
    }


migrate_Types_LoginFail : Evergreen.V28.Types.LoginFail -> Evergreen.V29.Types.LoginFail
migrate_Types_LoginFail old =
    case old of
        Evergreen.V28.Types.NotAsked ->
            Evergreen.V29.Types.NotAsked

        Evergreen.V28.Types.WrongUsernameOrPassword ->
            Evergreen.V29.Types.WrongUsernameOrPassword

        Evergreen.V28.Types.UsernameOrPasswordInvalid ->
            Evergreen.V29.Types.UsernameOrPasswordInvalid


migrate_Types_Menu : Evergreen.V28.Types.Menu -> Evergreen.V29.Types.Menu
migrate_Types_Menu old =
    { current = old.current |> Maybe.map migrate_Types_Lesson
    }


migrate_Types_Mods : Evergreen.V28.Types.Mods -> Evergreen.V29.Types.Mods
migrate_Types_Mods old =
    old


migrate_Types_MonoFont : Evergreen.V28.Types.MonoFont -> Evergreen.V29.Types.MonoFont
migrate_Types_MonoFont old =
    case old of
        Evergreen.V28.Types.PTMono ->
            Evergreen.V29.Types.PTMono

        Evergreen.V28.Types.RobotoMono ->
            Evergreen.V29.Types.RobotoMono

        Evergreen.V28.Types.UbuntuSansMono ->
            Evergreen.V29.Types.UbuntuSansMono

        Evergreen.V28.Types.JetBrainsMono ->
            Evergreen.V29.Types.JetBrainsMono

        Evergreen.V28.Types.IbmPlexMono ->
            Evergreen.V29.Types.IbmPlexMono


migrate_Types_Page : Evergreen.V28.Types.Page -> Evergreen.V29.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V28.Types.MenuPage p0 ->
            Evergreen.V29.Types.MenuPage (p0 |> migrate_Types_Menu)

        Evergreen.V28.Types.TypingPage p0 ->
            Evergreen.V29.Types.TypingPage (p0 |> migrate_Types_TypingModel)

        Evergreen.V28.Types.TypingStatisticPage p0 ->
            Evergreen.V29.Types.TypingStatisticPage (p0 |> migrate_Types_TypingStatisticModel)

        Evergreen.V28.Types.SettingsPage p0 ->
            Evergreen.V29.Types.SettingsPage p0

        Evergreen.V28.Types.StatisticPage p0 ->
            Evergreen.V29.Types.StatisticPage (p0 |> migrate_Types_Hover)

        Evergreen.V28.Types.AuthPage p0 ->
            Evergreen.V29.Types.AuthPage (p0 |> migrate_Types_AuthModel)

        Evergreen.V28.Types.InfoPage ->
            Evergreen.V29.Types.InfoPage


migrate_Types_PastDictation : Evergreen.V28.Types.PastDictation -> Evergreen.V29.Types.PastDictation
migrate_Types_PastDictation old =
    { errors = old.errors
    , lesson = old.lesson |> migrate_Types_Lesson
    , duration = old.duration
    , finished = old.finished
    }


migrate_Types_PastDictationBucket : Evergreen.V28.Types.Bucket -> Evergreen.V29.Types.PastDictationBucket
migrate_Types_PastDictationBucket old =
    old |> List.map migrate_Types_PastDictation


migrate_Types_Settings : Evergreen.V28.Types.Settings -> Evergreen.V29.Types.Settings
migrate_Types_Settings old =
    { blockOnError = old.blockOnError |> migrate_Types_WaitingFor
    , fontSize = old.fontSize
    , paddingLeft = old.paddingLeft
    , paddingRight = old.paddingRight
    , layout = old.layout |> migrate_Types_Layout
    , theme = old.theme |> migrate_Types_Theme
    , language = old.language |> migrate_Translation_Language
    }


migrate_Types_Theme : Evergreen.V28.Types.Theme -> Evergreen.V29.Types.Theme
migrate_Types_Theme old =
    { name = old.name |> migrate_Types_ThemeName
    , dark = old.dark
    , rounding = old.rounding
    , borderWidth = old.borderWidth
    , monoFont = old.monoFont |> migrate_Types_MonoFont
    }


migrate_Types_ThemeName : Evergreen.V28.Types.ThemeName -> Evergreen.V29.Types.ThemeName
migrate_Types_ThemeName old =
    case old of
        Evergreen.V28.Types.WheatField ->
            Evergreen.V29.Types.WheatField

        Evergreen.V28.Types.ElectricFields ->
            Evergreen.V29.Types.ElectricFields

        Evergreen.V28.Types.CandyLand ->
            Evergreen.V29.Types.CandyLand

        Evergreen.V28.Types.NeoClassic ->
            Evergreen.V29.Types.NeoClassic

        Evergreen.V28.Types.Dracula ->
            Evergreen.V29.Types.Dracula

        Evergreen.V28.Types.Contrast ->
            Evergreen.V29.Types.Contrast


migrate_Types_ToFrontend : Evergreen.V28.Types.ToFrontend -> Evergreen.V29.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V28.Types.GotSettings p0 ->
            Evergreen.V29.Types.GotSettings (p0 |> migrate_Types_Settings)

        Evergreen.V28.Types.KickOut ->
            Evergreen.V29.Types.KickOut

        Evergreen.V28.Types.RegisterFailed ->
            Evergreen.V29.Types.RegisterFailed

        Evergreen.V28.Types.LoginSuccessful ->
            Evergreen.V29.Types.LoginSuccessful

        Evergreen.V28.Types.LoginFailed ->
            Evergreen.V29.Types.LoginFailed

        Evergreen.V28.Types.UpdateStatistic p0 ->
            Evergreen.V29.Types.UpdateStatistic (p0 |> List.map migrate_Types_PastDictation)

        Evergreen.V28.Types.UpdateAppStatistic p0 ->
            Evergreen.V29.Types.UpdateAppStatistic (p0 |> migrate_Types_AppStatistic)

        Evergreen.V28.Types.UpdateAllPoints p0 ->
            Evergreen.V29.Types.UpdateAllPoints p0


migrate_Types_TypingModel : Evergreen.V28.Types.TypingModel -> Evergreen.V29.Types.TypingModel
migrate_Types_TypingModel old =
    { dictation = old.dictation |> migrate_Types_Dictation
    , madeError = old.madeError
    , errors = old.errors
    , mods = old.mods |> migrate_Types_Mods
    , lesson = old.lesson |> migrate_Types_Lesson
    , duration = old.duration
    , paused = old.paused
    , showKeyboard = old.showKeyboard
    , textOffset = old.textOffset
    , textSpeed = old.textSpeed
    }


migrate_Types_TypingStatisticModel : Evergreen.V28.Types.TypingStatisticModel -> Evergreen.V29.Types.TypingStatisticModel
migrate_Types_TypingStatisticModel old =
    { past = old.past |> migrate_Types_PastDictation
    , allPoints = old.allPoints
    , fromLesson = old.fromLesson
    }


migrate_Types_WaitingFor : Evergreen.V28.Types.WaitingFor -> Evergreen.V29.Types.WaitingFor
migrate_Types_WaitingFor old =
    case old of
        Evergreen.V28.Types.OneBackspace ->
            Evergreen.V29.Types.OneBackspace

        Evergreen.V28.Types.CorrectLetter ->
            Evergreen.V29.Types.CorrectLetter
