import csv
import random

layouts = [("qwertz", ["asdfjklö", "erui", "qwop", "tzgh", "vncm", "cxy", "büä"]),
("neo", ["uiaenrtd", "lchg", "fvxq", "wkos", "pbäm", "zöüßy"])]


with open('freq_dict_german.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    words = set([row[0] for row in spamreader])

    print("module Generated.Layouts exposing (..)")
    print("{-| This file was generated by convert.py -}")

    for layout in layouts:
        set = []
        names = []
        for i,must in enumerate([[* string] for string in layout[1]]):
            set.extend(must)
            # print(f"set is {set}, must is {must}")
            result = []
            for word in words:
                for char in [*word]:
                    if char not in set:
                        break
                else:
                    for item in must:
                        if item in [*word]:
                            result.append(word)
                            break

            result = [x for x in result if len(x) > 6]
            result.sort(key=len)
            result = result[:100]
            random.shuffle(result)
            value = ", ".join([f"\"{x}\"" for x in result])
            name = f"{layout[0]}{i}"
            names.append(name)
            print(f"{{-|set = {''.join(set)}\n\nmust = {''.join(must)}-}}\n{name} : List String\n{name} = [{value}]")

        print(f"{layout[0]} = [{','.join(names)}]")
